set (Boost_NO_SYSTEM_PATHS ON)
set (Boost_USE_MULTITHREADED ON)
set (Boost_USE_STATIC_LIBS ON)
set (Boost_USE_STATIC_RUNTIME OFF)
set (Boost_DEBUG OFF)
set (BOOST_ALL_DYN_LINK ON)
# For Windows set envirnoment variables as :
# set (BOOST_ROOT "D:/boost_1_72_0")
# set (BOOST_INCLUDEDIR "D:/boost_1_72_0/boost")
# set (BOOST_LIBRARYDIR "D:/boost_1_72_0/stage/lib")
find_package (Boost 1.66 REQUIRED COMPONENTS chrono)
if (Boost_FOUND)
  include_directories (SYSTEM ${Boost_INCLUDE_DIR})
endif ()